### ISSUE TITLE
pre-build binaries

### ISSUE THREAD

**Issue by c33s** [rgwood/systemctl-tui#12]
would be nice to have the binaries build on github and published under release assets.

**Comment by rgwood** [comment]
That would be handy.

I find working with GitHub Actions to be like pulling teeth, I'm not sure I will get to this anytime soon. But if someone wants to take this on that would be awesome.

**Comment by c33s** [comment]
i am with you according the github actions, i much prefer gitlab-ci. would it be an option to create a mirror on gitlab and build the packages there?
from gitlab side pull is sadly a premium feature but maybe github can automaticall push?

**Comment by rgwood** [comment]
> would it be an option to create a mirror on gitlab and build the packages there?

I don't think so, unfortunately. I don't want to maintain that kind of mirroring and I would be a little uncomfortable pointing people to a repo maintained by someone else for binaries.

Something like this might work for doing everything on GitHub: https://github.com/marketplace/actions/rust-release-binary

**Comment by rgwood** [comment]
OK, I spent a little time with [this GitHub Action](https://github.com/taiki-e/upload-rust-binary-action) and got this working. Binaries have been attached to https://github.com/rgwood/systemctl-tui/releases/tag/v0.3.1-alpha.2 and will be attached to regular releases going forward.

For now I'm only building for `aarch64-unknown-linux-musl` and `x86_64-unknown-linux-musl`. Could add more targets if needed.
