### ISSUE TITLE
Broken TUI under WSL2 + `systemctl: invalid option -- 'P'`

### ISSUE THREAD

**Issue by fadeevab** [rgwood/systemctl-tui#17]
`systemctl: invalid option -- 'P'` makes a noise in the TUI rendering.
Scrolling is affected.

![image](https://github.com/rgwood/systemctl-tui/assets/5967447/356ff64a-084e-4707-b963-2a0b8b452f2b)

**Comment by rgwood** [comment]
Thanks for the bug report. I haven’t observed this on WSL. What distro (name+version) are you using?

**Comment by rgwood** [comment]
Also, what version of systemctl-tui?

**Comment by honnorat** [comment]
Same problem here with version 0.3.4 on Ubuntu 20.04.

**Comment by fadeevab** [comment]
@rgwood Ubuntu 20.04, WSL2, systemctl-tui 0.3.4

**Comment by rgwood** [comment]
Thanks! I think there are a few issues here:
1. I'm using a `systemctl` CLI flag that is not present on older versions of systemd (it works on Ubuntu 22.04, systemd v249)
2. I'm not handling errors well in this particular path.

Not much I can do about 1 but I should be able to fix up 2. I'm a little busy this week+weekend but will aim to fix this up next week.

**Comment by kranurag7** [comment]
Please take your time @rgwood 

I started using it today and love the project so far. 

Adding my details from Fedora system attached to an external monitor. 

<details><summary>Details</summary>
<p>


![image](https://github.com/rgwood/systemctl-tui/assets/81210977/9e780298-4bcb-45e5-a4a9-c076970fdcd3)

</p>
</details>

**Comment by rgwood** [comment]
Fixed in v0.3.5.
