### ISSUE TITLE
logs doesn't show datetime of entries

### ISSUE THREAD

**Issue by rafaelfliu** [rgwood/systemctl-tui#19]
hihi, love this program! thanks for creating it.

but i'm wondering how come i do not see the datetimes of the log entries, whereas i see it on your previews.
could it be a terminal font/color issue?

i'm on:
rustc 1.78.0
ubuntu: 22.04

![image](https://github.com/rgwood/systemctl-tui/assets/10492540/17dd8fbd-f245-40ab-ad4b-73948ebfb0e8)

**Comment by rgwood** [comment]
Hi! Could you please confirm what version you're running (`systemctl-tui --version`)?

I'm guessing that this is a colour issue; I render the date as ANSI "dark gray"/"bright black", and maybe that doesn't show up in your terminal theme? https://github.com/rgwood/systemctl-tui/blob/2f80971151ec19275260598f03d73142472235ee/src/components/home.rs#L826

Open to other suggestions for the colour.

**Comment by rafaelfliu** [comment]
yeah, that's what i'm suspecting too.

i'm running on `systemctl-tui 0.3.5`

afraid that if we change it to some other color, there may be other users who will face the same issue too.
is there a way to make the colors customizable?

**Comment by rafaelfliu** [comment]
i think it's ok, i'll switch my terminal's theme instead. thanks for the help!

**Comment by rgwood** [comment]
> is there a way to make the colors customizable?

I'd prefer not to add a config system unless it's unavoidable.

By the way, what terminal are you using? Are you using a default colour theme or one you customized yourself?

**Comment by rgwood** [comment]
Closing this since I haven't been able to get necessary info
