### ISSUE TITLE
Colorize service names based on their status

### ISSUE THREAD

**Issue by k0ral** [rgwood/systemctl-tui#9]
`sysz` colorizes unit names to efficiently convey their status at a glance:
![image](https://github.com/rgwood/systemctl-tui/assets/524268/d9399f11-b4df-4389-883a-b40835d6d709)

This issue is about implementing the same feature in `systemctl-tui`.

**Comment by rgwood** [comment]
Good idea 👍

**Comment by rgwood** [comment]
Implemented in version 0.2.4.
